package com.gyzq.skinengine;

import android.app.Activity;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.View;

import com.gyzq.skin.SkinManager;

import java.util.ArrayList;

public class ListActivity extends Activity {

    RecyclerView recyclerView ;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_list);
        findViewById(R.id.chongzhi).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                SkinManager.getInstance().resetDefaultSkin();
            }
        });
        findViewById(R.id.huanfu).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                SkinManager.getInstance().loadSkin("/sdcard/app-debug.apk");
            }
        });

        recyclerView = findViewById(R.id.recycleview);
        LinearLayoutManager manager = new LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false);
        recyclerView.setLayoutManager(manager);
        ArrayList<String> list = new ArrayList<>();
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        list.add("发杀手全高清湖广会馆");
        list.add("噶是的噶是的噶十多个");
        list.add("噶是的噶十多个");
        list.add("发生地方上的");
        list.add("过热和各位好歌曲和");
        recyclerView.setAdapter(new ListAdapter(list));
    }
}